version: '3'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4-debian-10
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: vking34
    ports:
      - "27017:27017"
    volumes:
      - cz_data_feeder:/bitnami/mongodb

volumes:
  cz_data_feeder:
    driver: local
